### ISSUE TITLE
Cannot install execSync v1.0.2 error

### ISSUE THREAD

**Issue by dodozhang21** [cri5ti/grunt-shell-spawn#30]
I get the following error when I tried 

npm install grunt-shell-spawn --save-dev

> execSync@1.0.2 install d:\cq\cq-bhg\ui\node_modules\grunt-shell-spawn\node_modules\execSync
> node install.js

[execsync v1.0.2] Attempting to compile native extensions.
{ [Error: spawn ENOENT] code: 'ENOENT', errno: 'ENOENT', syscall: 'spawn' }
[execSync v1.0.2]
    Native code compile failed!!
    Will try to use win32 extension.
grunt-shell-spawn@0.3.1 node_modules\grunt-shell-spawn
└── execSync@1.0.2 (temp@0.5.1)

I'm running 

$ node --version
v0.10.35

Any idea why?

Thanks

**Comment by felixbillon** [comment]
:+1:

**Comment by sbryfcz** [comment]
From here: https://github.com/mgutz/execSync/issues/24


I was able to get it to work with the following steps:

npm install -g node-gyp
Install Python https://www.python.org/download/releases/2.7.3#download
CD node_modules\grunt-favicons\node_modules\execSync
Assume you have Visual Studio 2013 installed ...
node-gyp rebuild --msvs=2013
If you look at the source you will see that the error message "execSync incompatible with installed nodejs" is thrown for any exception, there is no test being done for versions, it's misleading.

**Comment by novice3030** [comment]
I still have this error but the fix didn't work for me

**Comment by woojoo666** [comment]
Thanks for the tip @sbryfcz ! Installing node-gyp using [the official instructions](https://github.com/TooTallNate/node-gyp#installation) and executing `node-gyp rebuild` inside the node_modules\execSync directory worked for me!

**Comment by charlescarrari** [comment]
Thank you @sbryfcz! :)

**Comment by bittorture** [comment]
Closing due to merge of #35
