### ISSUE TITLE
Need maintainer to take over the repo

### ISSUE THREAD

**Issue by dandv** [cri5ti/grunt-shell-spawn#33]
I'm sorry I haven't been able to cater to the repo much lately due to other work demands.

Would anyone want to take over?

**Comment by cri5ti** [comment]
Since there are still no maintainers, I'll try to squeeze some time to manage the project.

**Comment by jeking3** [comment]
The Apache Thrift javascript library uses grunt-shell-spawn.  It would be nice to have this maintained.

**Comment by jeking3** [comment]
The fix appears reasonably simple.  I'm on the Apache Thrift PMC and a Boost C++ Community Maintainer, so if you are comfortable with the transfer, I'll continue with maintenance.

When you stopped using grunt, what did you move to?

**Comment by jeking3** [comment]
Don't forget to tag and make a release... :)

**Comment by dandv** [comment]
> When you stopped using grunt, what did you move to?

As the link in my comment about that suggests, I've just been using npm.

Also, it turns out I can't add collaborators to this repository. Hey @cri5ti, you still around?

**Comment by cri5ti** [comment]
Hi @jeking3, thank you for taking over. 
You are now a collaborator to the repository.  
Would you like me to transfer the repository to your user as well?

**Comment by jeking3** [comment]
That would make it possible to do things like add CI, just make me an admin and you can keep the repository in your name... it's totally up to you.  Either way works.
